### ISSUE TITLE
Components to be modified

### ISSUE THREAD

**Issue by maxime-carabina** [raccord-io/ui-kit#15]
This is a list of components to me modified:

- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22

-----------------------------------------------

**⚠️ WARNING ⚠️** : Don't forget to :
- turn these TODOs into issue.
- create a branch and link it to this new issue.

**Comment by Clement-Fernandes** [comment]
Every component has been modified and I created a pull request for each component
